In [2]:
import pandas as pd

df = pd.read_csv("hf://datasets/bitext/Bitext-customer-support-llm-chatbot-training-dataset/Bitext_Sample_Customer_Support_Training_Dataset_27K_responses-v11.csv")

In [3]:
df.shape

(26872, 5)

In [4]:
df.head()

,flags,instruction,category,intent,response
0,B,question about cancelling order {{Order Number}},ORDER,cancel_order,I've understood you have a question regarding ...
1,BQZ,i have a question about cancelling oorder {{Or...,ORDER,cancel_order,I've been informed that you have a question ab...
2,BLQZ,i need help cancelling puchase {{Order Number}},ORDER,cancel_order,I can sense that you're seeking assistance wit...
3,BL,I need to cancel purchase {{Order Number}},ORDER,cancel_order,I understood that you need assistance with can...
4,BCELN,"I cannot afford this order, cancel purchase {{...",ORDER,cancel_order,I'm sensitive to the fact that you're facing f...

In [5]:
df.groupby('category').count()

              flags  instruction  intent  response
category
ACCOUNT        5986         5986    5986      5986
CANCEL          950          950     950       950
CONTACT        1999         1999    1999      1999
DELIVERY       1994         1994    1994      1994
FEEDBACK       1997         1997    1997      1997
INVOICE        1999         1999    1999      1999
ORDER          3988         3988    3988      3988
PAYMENT        1998         1998    1998      1998
REFUND         2992         2992    2992      2992
SHIPPING       1970         1970    1970      1970
SUBSCRIPTION    999          999     999       999

In [6]:
df[df['category'] == 'CANCEL'].head()

,flags,instruction,category,intent,response
2968,BCLWZ,"I can't ifnd the bloody termination charge, I ...",CANCEL,check_cancellation_fee,No worries! I'll assist you in finding the ter...
2969,BIL,what is the fee for canceling the contract?,CANCEL,check_cancellation_fee,To inquire about the cancellation fee for your...
2970,BILP,could I check the withdrawal charge?,CANCEL,check_cancellation_fee,Positively! I can help you with the informatio...
2971,BLQ,i need help to see the early termination penalty,CANCEL,check_cancellation_fee,Absolutely! To view the early termination pena...
2972,BLQ,need assistance to see the withdrawal fee,CANCEL,check_cancellation_fee,Indeed! I'm here to help you with checking the...

Буду использовать только категорию отмены

In [7]:
df = df[df['category'] == 'CANCEL'].copy()

In [8]:
df['instruction'].isna().sum()

np.int64(0)

In [9]:
df['instruction'].duplicated().sum()

np.int64(0)

In [10]:
df["instruction_len"] = df["instruction"].astype(str).str.len()
df["response_len"] = df["response"].astype(str).str.len()

print(df["instruction_len"].mean())
print(df["response_len"].mean())

print(df[["instruction_len", "response_len"]].describe())

43.96842105263158
260.8663157894737
       instruction_len  response_len
count       950.000000    950.000000
mean         43.968421    260.866316
std           8.629907    101.290660
min          14.000000     58.000000
25%          38.000000    184.000000
50%          44.000000    249.000000
75%          50.750000    329.000000
max          60.000000    638.000000

In [11]:
df["instruction_words"] = df["instruction"].astype(str).str.split().str.len()
df["response_words"] = df["response"].astype(str).str.split().str.len()

print(df["instruction_words"].mean())
print(df["response_words"].mean())

print(df[["instruction_words", "response_words"]].describe())

8.16842105263158
43.92842105263158
       instruction_words  response_words
count         950.000000      950.000000
mean            8.168421       43.928421
std             2.302940       16.805436
min             2.000000        9.000000
25%             7.000000       31.000000
50%             8.000000       42.000000
75%            10.000000       55.000000
max            15.000000      103.000000

In [12]:
df.sort_values(by=['instruction_words'])

,flags,instruction,category,intent,response,instruction_len,response_len,instruction_words,response_words
3349,BLZ,withrdawal penalty,CANCEL,check_cancellation_fee,Absolutely! To check the withdrawal penalty fo...,18,293,2,44
3330,BLM,termination fees,CANCEL,check_cancellation_fee,I'm happy to help! I can help you with checkin...,16,194,2,33
3359,BL,cancellation penalty,CANCEL,check_cancellation_fee,Unquestionably! Let me provide you with the de...,20,418,2,66
3320,BLM,termination charges,CANCEL,check_cancellation_fee,Positively! To check the termination charges a...,19,361,2,59
3719,BL,withdrawal fee,CANCEL,check_cancellation_fee,Certainly! The withdrawal fee for canceling yo...,14,287,2,45
...,...,...,...,...,...,...,...,...,...
3441,BEL,I do not know what I have to do to see the ter...,CANCEL,check_cancellation_fee,"No worries, I can guide you on how to check th...",58,270,14,45
3829,BELQ,i do not know what i need to do to check the t...,CANCEL,check_cancellation_fee,"No worries, I'll guide you through the process...",60,79,14,13
3116,BLM,I don't know what I have to do to see the earl...,CANCEL,check_cancellation_fee,"No problem! To view the early exit fees, you c...",57,205,14,38
3655,BEL,I do not know what I need to do to see the ear...,CANCEL,check_cancellation_fee,No problem! I can help you find the informatio...,60,241,15,42
3506,BELMQ,i do not know what i have to do to see the ear...,CANCEL,check_cancellation_fee,No problem! I can guide you through the proces...,58,456,15,82

In [13]:
df.sort_values(by=['response_words'])

,flags,instruction,category,intent,response,instruction_len,response_len,instruction_words,response_words
3260,BLQ,i need help seeing the withdrawal fee,CANCEL,check_cancellation_fee,Unquestionably! Let me help you check the with...,37,59,7,9
3605,BELQ,i do not know how to check the withdrawal charge,CANCEL,check_cancellation_fee,Sure! Let me help you with checking the withdr...,48,58,10,10
3882,BLMQ,i want help seeing the early exit penalties,CANCEL,check_cancellation_fee,Definitely! I can help you review the early te...,43,61,8,10
3884,BLQ,want assistance seeing the withdrawal charge,CANCEL,check_cancellation_fee,Positively! I'm here to assist you with viewin...,44,70,6,11
3073,BILM,how to check the early exit penalties?,CANCEL,check_cancellation_fee,"Sure, I can assist you with verifying the earl...",38,70,7,11
...,...,...,...,...,...,...,...,...,...
3064,BLQ,need assistance seeing the withdrawal penalty,CANCEL,check_cancellation_fee,Certainly! I can assist you in checking the wi...,45,600,6,99
3745,BILM,can you help me see the withdrawal fees?,CANCEL,check_cancellation_fee,"Of course, I'd be happy to help you understand...",40,632,8,100
3111,BILM,what are the withdrawal fees?,CANCEL,check_cancellation_fee,I'm on it! I can provide you with information ...,29,631,5,102
3250,BIL,what do I need to do to see the early terminat...,CANCEL,check_cancellation_fee,Unquestionably! Let me guide you on the steps ...,58,612,12,102
3814,BILMZ,what do I have to do to check the early exit f...,CANCEL,check_cancellation_fee,"Sure! To check the early exit fees, you can fo...",51,638,13,103

In [ ]:
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig

model_name = "mistralai/Mistral-7B-Instruct-v0.3"

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_use_double_quant=True,
    bnb_4bit_compute_dtype=torch.float16,
)

tokenizer = AutoTokenizer.from_pretrained(model_name)
tokenizer.pad_token = tokenizer.eos_token

model = AutoModelForCausalLM.from_pretrained(
    model_name,
    quantization_config=bnb_config,
    device_map="auto",
)

Fetching 3 files:   0%|          | 0/3 [00:00<?, ?it/s]